title: Miao Xi # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Love Data and passionate about designing digital products that help to make a difference!
  <br><br>
  Experienced in financial services but love challenges from all industries!
  <br><br>
  <a href="https://www.linkedin.com/in/miao-xi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
