title: Miao Xi # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
ex-Data & Analytics, Digital Product Analyst <b>@HSBC</b>
<br>
 ex-Data Engineer <b>@mindzie. Inc</b>
<br>
Data Science, Social Science Research Assistant <b>@UofT</b>, <b>@IBM</b>
<br>
Looking for the next chapter of my adventure in data world!
<br><br>

  <a href="https://www.linkedin.com/in/miao-xi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
